name: Github CLI

on: 
  push:
    paths:
      - '.github/workflows/gh.yaml'
  workflow_dispatch: #maunual trigger

jobs:
          
  cli: 
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
  
    
  

    

    

